# Generated by Django 5.1.5 on 2025-04-30 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('message_subject', models.CharField(max_length=100, verbose_name='message subject')),
                ('message', models.TextField(verbose_name='message')),
                ('date_time', models.DateTimeField(auto_now_add=True, verbose_name='date time')),
            ],
        ),
    ]
