# Generated by Django 5.1.5 on 2025-05-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalRadio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_brand', models.CharField(max_length=150, verbose_name='title brand')),
                ('brand', models.CharField(max_length=100, verbose_name='brand')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('Price_without_discount', models.PositiveIntegerField(verbose_name='price without discount')),
                ('discounted_price', models.PositiveIntegerField(verbose_name='price with discount')),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Digital Radios',
            },
        ),
    ]
