# Generated by Django 5.1.5 on 2025-05-10 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0010_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('province', models.CharField(max_length=150, verbose_name='province')),
                ('city', models.CharField(max_length=150, verbose_name='city ')),
                ('full_address', models.CharField(max_length=500, verbose_name='full address')),
                ('postal_code', models.CharField(max_length=50, verbose_name='postal code')),
                ('date_time_created', models.DateTimeField(auto_now_add=True, verbose_name='date time created')),
                ('date_time_modified', models.DateTimeField(auto_now=True, verbose_name='date modified')),
            ],
        ),
    ]
