# Generated by Django 5.1.5 on 2025-05-11 09:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='date_time_created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date time created'),
        ),
    ]
