# Generated by Django 5.1.5 on 2025-05-08 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_myuser_groups_myuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 8, 12, 16, 34, 997783, tzinfo=datetime.timezone.utc)),
        ),
    ]
