# Generated by Django 5.1.5 on 2025-05-11 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 11, 9, 17, 43, 379727, tzinfo=datetime.timezone.utc)),
        ),
    ]
