# Generated by Django 5.1.5 on 2025-05-14 05:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 5, 4, 25, 781967, tzinfo=datetime.timezone.utc)),
        ),
    ]
