# Generated by Django 5.1.5 on 2025-05-14 05:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_otpcode_expire_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire_time',
            field=models.DateTimeField(default=datetime.datetime(2025, 5, 14, 5, 16, 45, 883095, tzinfo=datetime.timezone.utc)),
        ),
    ]
