# Generated by Django 5.1.5 on 2025-05-03 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Brand Name')),
            ],
            options={
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('price_without_discount', models.PositiveIntegerField(verbose_name='price without discount')),
                ('price_with_discount', models.PositiveIntegerField(verbose_name='price with discount')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='image')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('rating', models.CharField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], max_length=10, verbose_name='rating')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='shop.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'Phone',
                'verbose_name_plural': 'Phones',
                'ordering': ['title'],
                'indexes': [models.Index(fields=['title', 'brand'], name='shop_phone_title_a70e49_idx')],
            },
        ),
    ]
