# Generated by Django 5.1.5 on 2025-05-02 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryDigitalProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('description', models.CharField(blank=True, max_length=700, verbose_name='description for category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ProductsTypeDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='نام')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.categorydigitalproducts', verbose_name='گروه')),
            ],
            options={
                'verbose_name': 'product type digital',
                'verbose_name_plural': 'product type digital',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProductsDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_product', models.CharField(max_length=100, verbose_name='name product')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('price', models.PositiveIntegerField(verbose_name='price ')),
                ('date_time_add', models.DateTimeField(auto_now_add=True, verbose_name='date time add')),
                ('digital_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.productstypedigital', verbose_name='digital_group')),
            ],
            options={
                'verbose_name': 'products digital ',
                'verbose_name_plural': 'products digital ',
                'ordering': ['title'],
            },
        ),
    ]
