# Generated by Django 5.1.5 on 2025-05-08 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Brand Name')),
            ],
            options={
                'verbose_name': 'LaptopBrand',
                'verbose_name_plural': 'LaptopBrand',
            },
        ),
        migrations.AddField(
            model_name='phone',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='active ?'),
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='title')),
                ('text', models.TextField(verbose_name='text')),
                ('price_without_discount', models.PositiveIntegerField(verbose_name='price without discount')),
                ('price_with_discount', models.PositiveIntegerField(verbose_name='price with discount')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cover/', verbose_name='image')),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='active ?')),
                ('release_date', models.DateField(blank=True, null=True, verbose_name='Release Date')),
                ('rating', models.CharField(blank=True, choices=[(1, '⭐'), (2, '⭐⭐'), (3, '⭐⭐⭐'), (4, '⭐⭐⭐⭐'), (5, '⭐⭐⭐⭐⭐')], max_length=10, verbose_name='rating')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='shop.brand', verbose_name='Brand')),
            ],
            options={
                'verbose_name': 'laptop',
                'verbose_name_plural': 'laptop',
                'ordering': ['release_date'],
                'indexes': [models.Index(fields=['title', 'brand'], name='shop_laptop_title_44a984_idx')],
            },
        ),
    ]
