# Generated by Django 5.1.5 on 2025-05-02 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='date_time_add',
        ),
    ]
