# Generated by Django 5.1.5 on 2025-05-08 12:54

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_laptopbrand_phone_is_active_laptop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='text',
            field=ckeditor.fields.RichTextField(verbose_name='text'),
        ),
    ]
