# Generated by Django 5.1.5 on 2025-05-08 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_laptop_text_alter_phone_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='laptops', to='shop.laptopbrand', verbose_name='Brand'),
        ),
    ]
