# Generated by Django 5.1.5 on 2025-05-10 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_commentphone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentphone',
            name='score',
            field=models.CharField(choices=[('5', 'perfect'), ('4', 'good'), ('3', 'normal'), ('2', ' bad'), ('1', 'very bad')], max_length=2),
        ),
    ]
